language: rust
sudo: false
rust: nightly
services: docker
dist: trusty

matrix:
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu CC=gcc-7 CXX=g++-7
      name: "x86_64-unknown-linux-gnu + SSE2"
      install: travis_retry rustup component add rustfmt-preview
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - os: osx
      env: TARGET=x86_64-apple-darwin
      name: "x86_64-apple-darwin + SSE2"
      install: travis_retry rustup component add rustfmt-preview
      script: ci/run.sh
      osx_image: xcode9.4
install:
  - travis_retry rustup target add $TARGET
  - travis_retry rustup component add rustfmt-preview
script: 
  - cargo generate-lockfile
  - ./ci/run.sh
