language: rust
sudo: false
rust: nightly

matrix:
  fast_finish: true
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      name: "x86_64-unknown-linux-gnu + SSE2"
      install: true
    - os: osx
      env: TARGET=x86_64-apple-darwin
      name: "x86_64-apple-darwin + SSE2"
      install: true
      script: ci/run.sh
      osx_image: xcode9.4
install: travis_retry rustup target add $TARGET
script: 
  - cargo generate-lockfile
  - ./ci/run.sh
